mod 'puppet/nginx', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
# module dependencies relating to yum_cron
mod 'treydock/yum_cron'
mod 'puppetlabs/inifile'
mod 'herculesteam/augeasproviders_shellvar'
mod 'herculesteam/augeasproviders_core'
